### ISSUE TITLE
403 Error on Trigger a Self Assessment Tax Calculation [test only] 

### ISSUE THREAD

**Issue by johnhemming** [hmrc/individual-calculations-api#136]
I have had a go at running a test version of all the new tax calculation APIs. All of them work (in the sense of a response code 200) apart from the above one which gives a 403 error.
I raised this on another repository and was asked to raise it here:

I have used the write:selfassessment scope. It gives this error:
code":"CLIENT_OR_AGENT_NOT_AUTHORISED","message":"The client and/or agent is not authorised"} {}

I tried out read:selfassessment to see what happens and that said the scope was wrong, which of course it is.

All the other ones work, however.

I had a response to this about scopes.   I did in fact give the scope information in the original question.  Hence I have used the right scope (and I get a different error if I use the wrong scope).

**Comment by mtd-api-team** [comment]
Hi @johnhemming 

Please note the hyphen in `write:self-assessment`. Did you definitely include this hyphen when authorising your application?

**Comment by johnhemming** [comment]
I definitely have the scope right as it is the same scope as all of the other self assessment write ones.   I don't set it up from new I have a constant in my code which I use for sandbox and production.

It is quite possible that I am the only person testing this particular API as I was the only person testing the losses API when I was testing those.

I will run it again in a minute or so and send you details of that so you can look at the logs.

**Comment by johnhemming** [comment]
I have just run it again and it works now.  Thanks for fixing it.

**Comment by mtd-api-team** [comment]
Glad to hear it's working now.
