### ISSUE TITLE
Number of decimal places for 'totalIncomeTaxAndNicsDue'

### ISSUE THREAD

**Issue by ac000** [hmrc/individual-calculations-api#217]
The documentation for  [/individuals/calculations/{nino}/self-assessment/{calculationId}](https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/individual-calculations-api/1.0#self-assessment_retrieve-self-assessment-tax-calculation-metadata_get_accordion) says that the value for the 'totalIncomeTaxAndNicsDue' field will be between -99999999999.99 and 99999999999.99

Note the two decimal places.

However, in the test-api at least, it is being returned like

```JSON
"totalIncomeTaxAndNicsDue": 5021.1099999999997,
```
So, is it meant to only be to two decimal places or do we need to cater for more? and if so what rounding algorithm should be used for halves?

**Comment by hmrc-api-team** [comment]
Hi @ac000,

Can you confirm for me which gov-test-scenario you are using to get this result. The responses on this API are canned, and that particular value shouldn't be possible from looking at the options on our end. We do have `5022.11` as an option in the default response though, so it's possible that something weird might be happening between you and the API.

Kind regards,
MTD API Team

**Comment by ac000** [comment]
HI,

I'm not specifying any Gov-Test-Scenario header so it's just the default.

In fact I'm seeing a lof values from various APIs which say they should only have 2 decimal places but are coming out like the above.

Hmm, let me try a raw request and check the raw response...

**Comment by ac000** [comment]
OK.

Looks like possibly a bug in the JSON library I'm using, checking the raw response from curl, I see it coming through as

```JSON
"totalIncomeTaxAndNicsDue":5021.11,
```

Sorry for the noise.
