### ISSUE TITLE
Get calculation by calculationID

### ISSUE THREAD

**Issue by kandarpAShah** [hmrc/individual-calculations-api#223]
Hello, as per [this link](https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/individual-calculations-api/1.0#endpoints) - we can get data after getting calculation ID. I would like to confirm, is it safe to assume when we have calculation Id that means calculation is completed?

**Comment by ac000** [comment]
It's not 100% clear.

According to the [_Trigger a Self Assessment Tax Calculation_](https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/individual-calculations-api/1.0#self-assessment_trigger-a-self-assessment-tax-calculation_post_accordion) endpoint text from Individual Calculations

> It can take up to 5 seconds for a Calculation ID to be returned when triggering a tax calculation.

Now, the old [_Trigger a tax calculation_](https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/self-assessment-api/2.0#tax-calculations_trigger-a-tax-calculation_post_accordion) endpoint from Self-Assessment would return a 202 Accepted with a JSON body of

```JSON
{
  "etaSeconds": 5
}
```

The new enpoint from Individual Calculations still returns a 202 Accepted, but it also a returns a fuller JSON body including a calculation ID.

My understanding is that after calling this endpoint you would then call the [_Retrieve Self Assessment Tax Calculation Metadata_](https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/individual-calculations-api/1.0#self-assessment_retrieve-self-assessment-tax-calculation-metadata_get_accordion) endpoint and you should allow for the fact that it may take 5 seconds fo this to return a result.

I'm working on the assumption that if I call the metadata endpoint before the calculation has completed I will get a 404 Not Found and should try again after a delay.

It would be useful to get some clarification on exactly how this is supposed to work.

**Comment by hmrc-api-team** [comment]
Hi @kandarpAShah sorry this wasn't responded to.

To answer the question, when the calculation is triggered, an ID is generated and returned. However the calculation is still being processed. It is recommended that you wait at least 5 seconds before making a request to Retrieve a Tax Calculation endpoints.

I'll close this issue, but feel free to open it and comment if you have any further issues or questions. Thanks
